name: PHP Composer

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: Install dependencies
                run: composer install

            -   name: Install PHP-cs-fixer
                run: composer --working-dir=tools/php-cs-fixer install

            -   name: Run PHPUnit
                run: vendor/bin/phpunit tests/GildedRoseTest.php

            -   name: Run PHPStan
                run: vendor/bin/phpstan analyse src

            -   name: Run Psalm
                run: vendor/bin/psalm src

            -   name: Run PHP-cs-fixer
                run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src




